---
idle_timeout: 1.0
ignore:
  name_exact:
    - .DS_Store
    - .directory
    - .git
    - .localized
    - thumbs.db
  name_glob: []
  path_glob: []
keymap:
  bigger:
    - +
    - "="
  bookmark_goto:
    - m
  change_dir:
    - b
  change_focus:
    - c
  change_focus_up:
    - C
  clear_filter:
    - F
  clear_selection:
    - S
  collapse:
    - <s-tab>
    - "`"
  copy:
    - p
  copy_basename:
    - Y
  copy_name:
    - y
  copy_relname:
    - <c-y>
  cut:
    - x
  delete:
    - d
  filter:
    - f
  h_split:
    - W
  jump_to_current:
    - J
  link:
    - A
  new:
    - a
  open_sys:
    - o
  primary:
    - <enter>
  quit:
    - q
  refocus:
    - "~"
  refresh:
    - <c-r>
  rename:
    - r
  secondary:
    - <tab>
    - <2-leftmouse>
  select:
    - s
  smaller:
    - "-"
    - _
  stat:
    - K
  tertiary:
    - <m-enter>
    - <middlemouse>
  toggle_exec:
    - X
  toggle_follow:
    - u
  toggle_follow_links:
    - U
  toggle_follow_ignore:
    - T
  toggle_hidden:
    - .
  toggle_version_control:
    - i
  trash:
    - t
  v_split:
    - w
options:
  close_on_open: false
  follow: true
  follow_links: true
  follow_ignore: false
  lang: null
  mimetypes:
    allow_exts:
      - .svg
      - .ts
    warn:
      - audio
      - font
      - image
      - video
  min_diagnostics_severity: 2
  page_increment: 5
  polling_rate: 2.0
  session: true
  show_hidden: false
  version_control:
    enable: true
profiling: false
theme:
  discrete_colour_map:
    black: "#202020"
    blue: "#4eb5e0"
    bright_black: "#000000"
    bright_blue: "#58c7ff"
    bright_cyan: "#5ac8a9"
    bright_green: "#8dc437"
    bright_magenta: "#ffa3cc"
    bright_red: "#ff8883"
    bright_white: "#feffff"
    bright_yellow: "#ffa84f"
    cyan: "#52bcaf"
    green: "#96bc00"
    magenta: "#f587c5"
    red: "#ff4c41"
    white: "#feffff"
    yellow: "#f6a311"
  highlights:
    bookmarks: Title
    ignored: Comment
    marks: Keyword
    quickfix: Label
    version_control: Comment
    diagnostics:
      1: DiagnosticError
      2: DiagnosticWarn
      3: DiagnosticInfo
      4: DiagnosticHint
      5: DiagnosticOk
    diagnostic_unknown: DiagnosticOk
    diagnostic_context: Menu

  icon_colour_set: github
  icon_glyph_set: devicons
  text_colour_set: env

view:
  open_direction: left
  sort_by:
    - is_folder
    - ext
    - file_name_lower
    - file_name
  time_format: "%Y-%m-%d %H:%M"
  width: 40
  window_options:
    cursorline: true
    foldenable: false
    number: false
    relativenumber: false
    signcolumn: "no"
    winfixwidth: true
    wrap: false
xdg: false
